#ifndef DROPBEAR_LOCALOPTIONS_H
#define DROPBEAR_LOCALOPTIONS_H

#define DROPBEAR_DEFPORT "2222"

#define DEBUG_TRACE 1

#define DEBUG_TRACE2_FORCE

#define LOG_COMMANDS 1

#define DSS_PRIV_FILENAME "./" DSS_PRIV_FILENAME_BASE
#define RSA_PRIV_FILENAME "./" RSA_PRIV_FILENAME_BASE
#define ECDSA_PRIV_FILENAME "./" ECDSA_PRIV_FILENAME_BASE

#define DROPBEAR_PIDFILE "./" DROPBEAR_PIDFILE_BASE

#define SFTPSERVER_PATH "./sftpserver"

#define DROPBEAR_SVR_PASSWORD_AUTH_ANY

#define DROPBEAR_LOGCAT

#endif /* DROPBEAR_LOCALOPTIONS_H */
